version: '3.3'
services:
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - database:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  backend:
#    build:
#      context: ../backend
#      dockerfile: ../backend/Dockerfile
    image: frantsevich/bakend:latest
    restart: always
    volumes:
      - media_value:/app/media/
      - static_value:/app/static/
    depends_on:
      - db
  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    image: frantsevich/frontend:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
      - static_value:/var/html/static/
    depends_on:
      - backend
volumes:
  database:
  static_value:
  media_value:
