# Generated by Django 3.2.18 on 2023-03-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='media/static/image/', verbose_name='image'),
        ),
    ]
